project_id          = "liquid-kite-436018-c2"
region              = "europe-west1"
zone                = "europe-west1-b"
machine_type        = "e2-standard-4"
vm_name             = "de-stream"
ssh_key_file        = "./keys/mycreds.json"
